/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A family consists of different tiers of the same artifact, stone (including fragment form), or ingredient.
 */
export type Family = FamilyCore & {
  /**
   * Empty for ingredients.
   */
  effect: string;
  /**
   * Effect without verbs like "increases", matches effect_target in child tiers. Empty for ingredients.
   */
  effect_target: string;
  tiers: Tier[];
  [k: string]: unknown;
};
/**
 * ArtifactSpec.Name enum value
 */
export type AfxId =
  | 0
  | 3
  | 4
  | 5
  | 6
  | 7
  | 8
  | 9
  | 10
  | 11
  | 12
  | 21
  | 22
  | 23
  | 24
  | 25
  | 26
  | 27
  | 28
  | 29
  | 30
  | 1
  | 31
  | 32
  | 33
  | 34
  | 39
  | 36
  | 37
  | 38
  | 40
  | 13
  | 14
  | 15
  | 16
  | 17
  | 18
  | 19
  | 20
  | 35
  | 41
  | 42
  | 43
  | 2
  | 44
  | 45
  | 46
  | 47
  | 48
  | 49
  | 50
  | 51
  | 52;
/**
 * An item tier, or in other words, a specific item, with a name and an icon
 */
export type Tier = TierCore & {
  quality: number;
  crafting_xp?: number;
  odds_multiplier?: number;
  /**
   * Whether the item is craftable (false for T1 items, true otherwise)
   */
  craftable: boolean;
  /**
   * Whether this item's family supports rarities, i.e., true only for artifacts (doesn't matter if this specific tier has only common rarity).
   */
  has_rarities: boolean;
  /**
   * Possible rarity variants of this item (null if has_rarities is false).
   */
  possible_afx_rarities: null | AfxRarity[];
  has_effects: boolean;
  available_from_missions: boolean;
  effects: null | Effect[];
  recipe: null | Recipe;
  /**
   * Whether all of this item's ingredients are available from missions.
   */
  ingredients_available_from_missions: boolean;
  /**
   * For an item unobtainable from missions, the hard dependencies are the highest level mission-obtainable items in the crafting ingredient tree; i.e., the ingredients must be gathered in order to craft the item in question, no way to skip them.
   */
  hard_dependencies: null | Ingredient[];
  [k: string]: unknown;
};
/**
 * ArtifactSpec.Level enum value
 */
export type AfxLevel = 0 | 1 | 2 | 3;
/**
 * ArtifactSpec.Type enum value
 */
export type AfxType = 0 | 1 | 2 | 3;
/**
 * ArtifactSpec.Rarity enum value
 */
export type AfxRarity = 0 | 1 | 2 | 3;
export type Ingredient = TierCore & {
  count: number;
  [k: string]: unknown;
};

export interface EggIncArtifactsRelatedData {
  artifact_families?: Family[];
  [k: string]: unknown;
}
export interface FamilyCore {
  /**
   * A human-readable unique ID of the family based on its name
   */
  id: string;
  afx_id: AfxId;
  name: string;
  /**
   * ArtifactSpec.Type enum value
   */
  afx_type: 0 | 1 | 2;
  /**
   * Human-readable type of the family
   */
  type: "Artifact" | "Stone" | "Ingredient";
  /**
   * An unsigned integer key for sorting families based on type first, then the order of appearance on the quality ladder. This roughly matches how the game sorts families in the inventory system (with minor discrepancies around stones.)
   */
  sort_key: number;
  /**
   * afx_id's belonging to the family. For artifacts and ingredients, this only contains the family's own afx_id; for stones, this also contains the afx_id of the corresponding stone fragment.
   */
  child_afx_ids: AfxId[];
  [k: string]: unknown;
}
export interface TierCore {
  family?: FamilyCore;
  /**
   * A human-readable unique ID of the family based on its family name and tier number
   */
  id: string;
  afx_id: AfxId;
  afx_level: AfxLevel;
  name: string;
  /**
   * Positive tier number in the 4-tier structure of artifacts and stones (including fragments as tier 1), or 3-tier structure of ingredients.
   */
  tier_number: 1 | 2 | 3 | 4;
  /**
   * Name (qualifier) of the tier after stripping the common family name; 'Regular' if there's no specific qualifier.
   */
  tier_name: string;
  afx_type: AfxType;
  /**
   * Filename of the corresponding icon in the app's assets
   */
  icon_filename: string;
  [k: string]: unknown;
}
export interface Effect {
  afx_rarity: AfxRarity;
  rarity: string;
  odds_multiplier?: number;
  /**
   * The full effect description
   */
  effect: string;
  /**
   * Effect description sans the effect size (amount), common to all rarity levels of the same item.
   */
  effect_target: string;
  effect_size: string;
  effect_delta?: number;
  /**
   * Matches family's effect.
   */
  family_effect: string;
  /**
   * Number of slots; null if the family isn't supposed to have slots.
   */
  slots: number | null;
  [k: string]: unknown;
}
export interface Recipe {
  ingredients: Ingredient[];
  crafting_price: {
    /**
     * ArtifactsConfigurationResponse.ArtifactParameters.crafting_price
     */
    base: number;
    /**
     * ArtifactsConfigurationResponse.ArtifactParameters.crafting_price_low
     */
    low: number;
    /**
     * ArtifactsConfigurationResponse.ArtifactParameters.crafting_price_domain
     */
    domain: number;
    /**
     * ArtifactsConfigurationResponse.ArtifactParameters.crafting_price_curve
     */
    curve: number;
    /**
     * Golden eggs cost of crafting this item for the first time
     */
    initial: number;
    /**
     * Minimum golden eggs cost of crafting this item
     */
    minimum: number;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
